test_that("setup modes show the relevant inputs and YAML changes the topic count safely", {
  modes_browser_ready()
  path <- withr::local_tempfile()
  init_db(path)
  cfg <- app_config(path, "secret", "http://localhost:3838", poll_ms = 2500)
  app <- modes_browser_app(cfg, "mode-settings")
  modes_browser_moderator(app)
  app$wait_for_js("!!document.querySelector('#play_mode')")
  app$set_inputs(play_mode = "hot_seat")
  app$wait_for_js("$('#turn_secs').is(':visible') && !$('#round_secs').is(':visible')")
  expect_true(app$get_js("$('#roster').is(':visible')"))
  modes_browser_capture(app, "setup-hot-seat-mobile")
  app$set_inputs(play_mode = "group_device")
  app$wait_for_js("$('#group_names').is(':visible') && !$('#roster').is(':visible')")
  expect_true(app$get_js("$('#round_secs').is(':visible')"))
  example <- parse_settings(system.file(
    "extdata", "settings-example.yml", package = "brainwritR"
  ))
  expect_s3_class(example, "bw_settings")
  for (k in c(2L, 4L)) {
    settings <- example
    settings$topics <- rep(example$topics[1], k)
    for (i in seq_len(k)) {
      settings$topics[[i]] <- list(title = paste("Import", k, i),
                                   q1 = paste("Frage A", i), q2 = paste("Frage B", i))
    }
    settings$groups <- paste("Team", seq_len(k))
    file <- withr::local_tempfile(fileext = ".yml")
    write_settings(settings, file)
    app$upload_file(settings_file = file)
    app$wait_for_js(sprintf("document.querySelector('#t_title_%d')?.value === 'Import %d %d'",
                            k, k, k))
    app$wait_for_idle()
    expect_equal(app$get_js("Number(document.querySelector('#n_groups').value)"), k)
    for (i in seq_len(k)) {
      expect_equal(app$get_js(sprintf("document.querySelector('#t_title_%d').value", i)),
                   paste("Import", k, i))
      expect_equal(app$get_js(sprintf("document.querySelector('#t_q2_%d').value", i)),
                   paste("Frage B", i))
    }
    expect_false(app$get_js(sprintf("!!document.querySelector('#t_title_%d')", k + 1L)))
    expect_identical(read_table(path, "session")$status, "setup")
  }
  expect_true(app$get_js("document.documentElement.scrollWidth <= window.innerWidth"))
})

test_that("group buttons require confirmation to take over a canonical author", {
  modes_browser_ready()
  path <- new_db(withr::local_tempfile())
  exec_sql(path, "UPDATE session SET mode = 'group_device'")
  canonical <- claim_group(path, 1L)
  cfg <- app_config(path, "secret", "http://localhost:3838", poll_ms = 2500)
  app <- modes_browser_app(cfg, "group-claim")
  app$wait_for_js("!!document.querySelector('#group_choices button')")
  expect_match(app$get_js("document.body.innerText"), "Als Gruppe beitreten")
  modes_browser_capture(app, "group-claim-mobile")
  app$run_js("document.querySelector('#group_choices button').click()")
  app$wait_for_js("document.body.innerText.includes('bereits verbunden')")
  expect_match(app$get_js("document.body.innerText"), "bereits verbunden")
  expect_equal(nrow(read_table(path, "participants")), 1)
  expect_null(app$get_js("localStorage.getItem('bw_pid')"))
  app$click("group_confirm")
  app$wait_for_js("document.body.innerText.includes('Hallo Gruppe 1')")
  expect_identical(app$get_js("localStorage.getItem('bw_pid')"), canonical)
  expect_equal(nrow(read_table(path, "participants")), 1)
  expect_true(app$get_js("document.documentElement.scrollWidth <= window.innerWidth"))
})

test_that("hot seat hands off identity without leaking the previous author's text", {
  modes_browser_ready()
  path <- new_db(withr::local_tempfile(), n = 3)
  exec_sql(path, "UPDATE session SET mode = 'hot_seat'")
  start_session(path)
  first <- current_author(path)
  cfg <- app_config(path, "secret", "http://localhost:3838", poll_ms = 2500)
  app <- modes_browser_app(cfg, "hot-seat")
  app$wait_for_js("!!document.querySelector('#turn_start')")
  expect_match(app$get_js("document.body.innerText"), paste("Weitergeben an:", first$name))
  expect_false(app$get_js("!!document.querySelector('#join_name')"))
  expect_false(app$get_js("!!document.querySelector('#a1')"))
  modes_browser_capture(app, "hot-seat-handover-mobile")
  app$click("turn_start")
  app$wait_for_js("!!document.querySelector('#a1')")
  modes_browser_capture(app, "hot-seat-answer-mobile")
  app$set_inputs(a1 = "Erste Person entwickelt eine Idee", a2 = "Ein nächster Schritt")
  app$wait_for_js("!!document.querySelector('#submit_btn.shiny-bound-input')")
  app$click("submit_btn")
  app$wait_for_js("!!document.querySelector('#turn_start')")
  e <- read_table(path, "entries")
  expect_equal(nrow(e), 2)
  expect_true(all(e$pid == first$pid))
  expect_true(all(e$submitted == 1L))
  second <- current_author(path)
  expect_false(identical(second$pid, first$pid))
  expect_match(app$get_js("document.body.innerText"), paste("Weitergeben an:", second$name))
  app$click("turn_start")
  app$wait_for_js("!!document.querySelector('#a1')")
  expect_identical(app$get_js("document.querySelector('#a1').value"), "")
  expect_identical(app$get_js("document.querySelector('#a2').value"), "")
  expect_null(app$get_js("localStorage.getItem('bw_pid')"))
  expect_true(app$get_js("document.documentElement.scrollWidth <= window.innerWidth"))
})
