test_that("question counts preserve edits and round-trip through settings downloads", {
  modes_browser_ready()
  path <- withr::local_tempfile()
  init_db(path)
  app <- modes_browser_app(app_config(path, "secret", "http://localhost:3838"), "questions")
  modes_browser_moderator(app)
  app$wait_for_js("!!document.querySelector('#t_q2_1.shiny-bound-input')")
  app$set_inputs(n_groups = 2, n_rounds = 2)
  app$wait_for_js("!document.querySelector('#t_title_3')")
  app$set_inputs(t_nq_1 = 1, t_nq_2 = 3)
  app$wait_for_js("!!document.querySelector('#t_q3_2.shiny-bound-input')")
  app$set_inputs(t_title_1 = "A", t_q1_1 = "One prompt", t_title_2 = "B",
                 t_q1_2 = "First", t_q2_2 = "Second", t_q3_2 = "Third")
  app$set_inputs(t_nq_2 = 4)
  app$wait_for_js("!!document.querySelector('#t_q4_2.shiny-bound-input')")
  expect_identical(app$get_js("document.querySelector('#t_q3_2').value"), "Third")
  app$set_inputs(t_nq_2 = 3)
  app$wait_for_js("!document.querySelector('#t_q4_2')")
  app$wait_for_idle()
  settings <- parse_settings(app$get_download("dl_settings"))
  expect_identical(topic_questions(settings$topics[[1]]), "One prompt")
  expect_identical(topic_questions(settings$topics[[2]]), c("First", "Second", "Third"))
  app$click("setup_save")
  app$wait_for_js("!!document.querySelector('#start_btn')")
  expect_identical(get_settings(path)$topics, settings$topics)
})

test_that("weighted results update pseudonyms and download real binary formats", {
  modes_browser_ready()
  path <- variable_db(withr::local_tempfile())
  pid <- read_table(path, "participants")$pid[1]
  save_entry(path, pid, 2, 1, 1, 3, "A real answer", 1)
  maybe_advance(path, TRUE)
  maybe_advance(path, TRUE)
  open_plenum(path)
  set_weight(path, pid, read_table(path, "entries")$id[1], 100)
  close_plenum(path)
  app <- modes_browser_app(app_config(path, "secret", "http://localhost:3838"), "downloads")
  modes_browser_moderator(app)
  app$wait_for_js("!!document.querySelector('#mod_results')")
  app$wait_for_js("document.querySelector('#mod_results').innerText.includes('Alice')")
  app$set_inputs(anonymize = TRUE)
  app$wait_for_js("document.querySelector('#mod_results').innerText.includes('TN-01')")
  expect_false(app$get_js("document.querySelector('#mod_results').innerText.includes('Alice')"))
  expect_true(app$get_js("document.querySelector('#mod_results').innerText.includes('Third')"))
  app$run_js(paste0("Array.from(document.querySelectorAll('a'))",
                    ".find(x => x.textContent === 'Analyse & Plenum').click()"))
  app$wait_for_js("!!document.querySelector('#fig_weights img')")
  expect_false(app$get_js("!!document.querySelector('.shiny-output-error')"))
  pdf <- app$get_download("dl_pdf")
  expect_identical(readChar(pdf, 5, useBytes = TRUE), "%PDF-")
  expect_equal(pdftools::pdf_info(pdf)$pages, 3L)
  xlsx <- app$get_download("dl_xlsx")
  expect_identical(readChar(xlsx, 2, useBytes = TRUE), "PK")
  expect_length(openxlsx::getSheetNames(xlsx), 5L)
  rds <- readRDS(app$get_download("dl_rds"))
  expect_identical(rds$participants$name, c("TN-01", "TN-02"))
  expect_identical(topic_questions(rds$topics[2, ]), c("First", "Second", "Third"))
  csv <- utils::read.csv(app$get_download("dl_csv"))
  expect_identical(csv$Teilnehmer, "TN-01")
  md <- paste(readLines(app$get_download("dl_md")), collapse = "\n")
  expect_match(md, "F3:** Third", fixed = TRUE)
  expect_false(grepl("Alice", md, fixed = TRUE))
  weights <- utils::read.csv(app$get_download("dl_weights"))
  expect_identical(weights$Beitrag, "A real answer")
})
