test_that("variable questions validate and persist alongside legacy settings", {
  x <- variable_settings()
  config <- validate_settings(x)
  expect_s3_class(config, "bw_settings")
  file <- withr::local_tempfile()
  write_settings(config, file)
  expect_identical(parse_settings(file), config)
  for (value in list(character(), list(), NA_character_, c("OK", ""), 2, list(list("Q")))) {
    bad <- x
    bad$topics[[1]]$questions <- value
    expect_type(validate_settings(bad), "character")
  }
  path <- variable_db(withr::local_tempfile())
  expect_identical(get_settings(path), config)
  topics <- read_table(path, "topics")
  expect_identical(topic_questions(topics[1, ]), "One prompt")
  expect_identical(topic_questions(topics[2, ]), c("First", "Second", "Third"))
  expect_identical(question_text(topics, c(2, 1), c(3, 1)), c("Third", "One prompt"))
  init_db(path)
  expect_identical(get_settings(path), config)
  expect_identical(topic_questions(list(q1 = "Old 1", q2 = "Old 2")), c("Old 1", "Old 2"))
})

test_that("answers autosave and submit all configured questions and only those", {
  path <- variable_db(withr::local_tempfile())
  p <- read_table(path, "participants")
  pid <- p$pid[p$grp == 2]
  cfg <- app_config(path, "secret", "http://localhost:3838", poll_ms = 50)
  shiny::testServer(app_server(cfg), {
    session$setInputs(stored_pid = pid)
    expect_match(output$part_view$html, 'id="a3"', fixed = TRUE)
    session$setInputs(a1 = "", a2 = "", a3 = "")
    session$setInputs(a1 = "Answer one", a2 = "Answer two", a3 = "Answer three")
    session$elapse(1400)
    e <- read_table(path, "entries")
    expect_setequal(e$question, 1:3)
    expect_match(e$text[e$question == 3], "Answer three")
    session$setInputs(submit_btn = 1)
    expect_true(all(read_table(path, "entries")$submitted == 1))
    maybe_advance(path, TRUE)
    session$elapse(100)
    expect_false(grepl('id="a2"', output$part_view$html, fixed = TRUE))
    session$setInputs(a1 = "Only answer", a3 = "Stale third answer", submit_btn = 2)
    session$elapse(1400)
    e <- read_table(path, "entries")
    expect_identical(e$question[e$round == 2], 1L)
    expect_identical(e$text[e$round == 2], "Only answer")
  })
})

test_that("question context and pseudonyms react immediately in results", {
  path <- variable_db(withr::local_tempfile())
  pid <- read_table(path, "participants")$pid[1]
  save_entry(path, pid, 2, 1, 1, 3, "Final answer", 1)
  maybe_advance(path, TRUE)
  maybe_advance(path, TRUE)
  cfg <- app_config(path, "secret", "http://localhost:3838", poll_ms = 50)
  shiny::testServer(app_server(cfg), {
    session$setInputs(pin = "secret", pin_btn = 1)
    expect_match(output$mod_results$html, "Alice")
    expect_match(output$mod_results$html, "Third")
    session$setInputs(anonymize = TRUE)
    expect_false(grepl("Alice", output$mod_results$html, fixed = TRUE))
    expect_match(output$mod_results$html, "TN-01")
    expect_match(output$analytics_view$html, "Third")
    session$setInputs(anonymize = FALSE)
    expect_match(output$mod_results$html, "Alice")
  })
  expect_identical(read_table(path, "participants")$name[1], "Alice")
  open_plenum(path)
  set_weight(path, pid, read_table(path, "entries")$id[1], 100)
  d <- collect_data(path)
  expect_match(as.character(weights_ui(plenum_items(path, pid), d$topics)), "Third")
  results <- plenum_results(d$entries, d$topics, d$votes)
  expect_match(as.character(shiny::tagList(plenum_results_ui(results, d$topics))), "Third")
  expect_match(build_snapshot_md(d), "F3:** Third", fixed = TRUE)
  expect_match(build_md(path), "F3:** Third", fixed = TRUE)
  tokens <- bw_entry_tokens(transform(d$entries, text = "Third useful"), d$topics)
  expect_false("third" %in% unlist(tokens))
})

test_that("weighting chart and weighted PDF draw multiple unequal panels", {
  skip_if_not(capabilities("cairo"))
  path <- variable_db(withr::local_tempfile())
  pid <- read_table(path, "participants")$pid[1]
  for (q in 1:3) save_entry(path, pid, 2, 1, 1, q, paste("Idea", q), 1)
  save_entry(path, pid, 1, 1, 1, 1, "Other idea", 1)
  maybe_advance(path, TRUE)
  maybe_advance(path, TRUE)
  open_plenum(path)
  for (i in 1:4) set_weight(path, pid, i, 25)
  d <- collect_data(path)
  plot <- bw_plot_weights(plenum_results(d$entries, d$topics, d$votes), d$topics)
  withr::local_pdf(withr::local_tempfile(fileext = ".pdf"))
  expect_no_error(ggplot2::ggplotGrob(plot))
  file <- withr::local_tempfile(fileext = ".pdf")
  expect_no_error(build_report(d, file))
  expect_identical(readChar(file, 5, useBytes = TRUE), "%PDF-")
  expect_equal(pdftools::pdf_info(file)$pages, 3L)
})
