test_that("connections never recreate a missing session database", {
  path <- file.path(withr::local_tempdir(), "gone.sqlite")
  expect_error(db(path))
  expect_false(file.exists(path))
  init_db(path)
  pid <- add_participant(path, "Vor dem Loeschen")
  unlink(path)
  expect_error(save_entry(path, pid, 1, 1, 1, 1, "Verspaeteter Entwurf"))
  expect_false(file.exists(path))
})

test_that("a forced reset clears a session in any state", {
  path <- new_db(withr::local_tempfile(), n = 3)
  start_session(path)
  expect_false(reset_session(path))
  expect_true(reset_session(path, force = TRUE))
  expect_identical(read_table(path, "session")$status, "setup")
  expect_equal(nrow(read_table(path, "participants")), 0)
})

test_that("new sessions get their own database file, code and address", {
  main <- catalog_fixture()
  a <- create_session(main, "Kurs A")
  b <- create_session(main)
  expect_match(c(a, b), "^[2-9abcdefghjkmnpqrstuvwxyz]{6}$")
  expect_false(identical(a, b))
  expect_true(file.exists(file.path(dirname(main), "sessions", paste0(a, ".sqlite"))))
  expect_identical(read_table(session_path(main, a), "session")$status, "setup")
  listed <- list_sessions(main, "https://bw.example.org")
  expect_identical(listed$code, c(NA, a, b))
  expect_identical(listed$label[1:2], c("Standard-Session", "Kurs A"))
  expect_match(listed$label[3], "^Session ")
  expect_identical(listed$url, c("https://bw.example.org",
                                 paste0("https://bw.example.org?s=", c(a, b))))
  expect_identical(session_url("https://x.org/?lang=de", a), paste0("https://x.org/?lang=de&s=", a))
  expect_identical(listed$status, rep("setup", 3))
  expect_false(any(listed$archived))
})

test_that("session lists report live state and content counts from each file", {
  main <- catalog_fixture()
  code <- create_session(main, "Laufend")
  finish_with_entry(session_path(main, code))
  listed <- list_sessions(main, "http://localhost:3838")
  row <- listed[which(listed$code == code), ]
  expect_identical(row$status, "finished")
  expect_identical(row$mode, "individual")
  expect_equal(row$participants, 3)
  expect_equal(row$contributions, 1)
  expect_identical(row$topics, "Thema 1 \u00b7 Thema 2 \u00b7 Thema 3")
})

test_that("routes resolve participants and moderators to exactly one session", {
  main <- catalog_fixture()
  code <- create_session(main, "Kurs B")
  cfg <- app_config(main, "secret", "https://bw.example.org")
  standard <- resolve_route(cfg, list(mocksearch = "1"))
  expect_identical(standard$kind, "session")
  expect_false(standard$mod)
  expect_identical(standard$cfg$db_path, main)
  expect_identical(standard$cfg$base_url, "https://bw.example.org")
  coded <- resolve_route(cfg, list(s = toupper(code)))
  expect_identical(coded$cfg$db_path, session_path(main, code))
  expect_identical(coded$cfg$base_url, paste0("https://bw.example.org?s=", code))
  expect_identical(coded$cfg$label, "Kurs B")
  expect_true(resolve_route(cfg, list(mod = "1", s = code))$mod)
  expect_identical(resolve_route(cfg, list(s = "zzzzzz"))$kind, "missing")
  expect_identical(resolve_route(cfg, list(s = "../../x"))$kind, "missing")
  expect_identical(resolve_route(cfg, list(mod = "1", view = "sessions"))$kind, "sessions")
  expect_identical(resolve_route(cfg, list(view = "sessions"))$kind, "session")
  unlink(session_path(main, code))
  expect_identical(resolve_route(cfg, list(s = code))$kind, "missing")
})

test_that("restarting copies reviewed settings into a new session in setup", {
  main <- catalog_fixture()
  code <- create_session(main, "Kurs C")
  expect_null(rerun_session(main, code))
  topics <- rep(list(list(t = "Thema", a = "Frage 1", b = "Frage 2")), 3)
  expect_null(configure_session(session_path(main, code), 3, 2, 120, topics))
  again <- rerun_session(main, code)
  expect_match(again, "^[2-9a-z]{6}$")
  route <- resolve_route(app_config(main, "x", "http://localhost:3838"), list(mod = "1", s = again))
  expect_identical(route$prefill, get_settings(session_path(main, code)))
  expect_identical(route$cfg$label, "Kurs C (Wiederholung)")
  expect_identical(read_table(session_path(main, again), "session")$status, "setup")
  expect_identical(rerun_session(main, again), NULL)
  expect_null(configure_session(main, 3, 3, 300, topics))
  standard_again <- rerun_session(main, NA)
  expect_identical(list_sessions(main, "http://x.org")$label[4], "Standard-Session (Wiederholung)")
  expect_match(standard_again, "^[2-9a-z]{6}$")
})

test_that("only finished sessions are archived and archiving is reversible", {
  main <- catalog_fixture()
  code <- create_session(main, "Kurs D")
  expect_match(archive_session(main, code), "beendete")
  finish_with_entry(session_path(main, code))
  expect_null(archive_session(main, code))
  cfg <- app_config(main, "secret", "http://localhost:3838")
  expect_identical(resolve_route(cfg, list(s = code))$kind, "archived")
  moderator <- resolve_route(cfg, list(mod = "1", s = code))
  expect_identical(moderator$kind, "session")
  expect_true(moderator$cfg$archived)
  expect_true(list_sessions(main, "http://x.org")$archived[2])
  expect_null(restore_session(main, code))
  expect_false(list_sessions(main, "http://x.org")$archived[2])
  expect_identical(resolve_route(cfg, list(s = code))$kind, "session")
})

test_that("archiving the standard session moves its results and frees the base address", {
  main <- catalog_fixture()
  finish_with_entry(main, "Standardidee")
  expect_null(archive_session(main, NA))
  listed <- list_sessions(main, "http://x.org")
  expect_identical(listed$status[1], "setup")
  expect_equal(nrow(read_table(main, "entries")), 0)
  expect_true(listed$archived[2])
  expect_match(listed$label[2], "^Standard-Session vom ")
  copy <- session_path(main, listed$code[2])
  expect_identical(read_table(copy, "entries")$text, "Standardidee")
  expect_identical(read_table(copy, "session")$status, "finished")
  con <- db(copy)
  on.exit(DBI::dbDisconnect(con))
  expect_false(DBI::dbExistsTable(con, "catalog"))
  expect_match(archive_session(main, NA), "beendete")
})

test_that("deleting removes a session completely while the standard session is reset", {
  main <- catalog_fixture()
  code <- create_session(main, "Kurs E")
  path <- session_path(main, code)
  new_db(path, n = 3)
  start_session(path)
  expect_null(delete_session(main, code))
  expect_false(any(file.exists(paste0(path, c("", "-wal", "-shm")))))
  expect_identical(list_sessions(main, "http://x.org")$code, NA_character_)
  expect_identical(delete_session(main, code), "Session nicht gefunden.")
  new_db(main, n = 3)
  start_session(main)
  expect_null(delete_session(main, NA))
  expect_identical(read_table(main, "session")$status, "setup")
  expect_equal(nrow(read_table(main, "participants")), 0)
})

test_that("startup migrates every catalogued session file to the current schema", {
  main <- catalog_fixture()
  code <- create_session(main, "Aus Version 0.4")
  path <- session_path(main, code)
  exec_sql(path, "DROP TABLE votes")
  exec_sql(path, "ALTER TABLE session DROP COLUMN plenum_turn")
  exec_sql(path, "ALTER TABLE session DROP COLUMN plenum")
  gone <- create_session(main, "Datei fehlt")
  unlink(session_path(main, gone))
  migrate_sessions(main)
  expect_identical(read_table(path, "session")$plenum, "none")
  expect_equal(nrow(read_table(path, "votes")), 0)
  expect_false(file.exists(session_path(main, gone)))
})

test_that("starting the app upgrades catalogued session files from 0.4.0", {
  main <- catalog_fixture()
  code <- create_session(main, "Aus Version 0.4")
  path <- session_path(main, code)
  exec_sql(path, "DROP TABLE votes")
  exec_sql(path, "ALTER TABLE session DROP COLUMN plenum_turn")
  exec_sql(path, "ALTER TABLE session DROP COLUMN plenum")
  testthat::local_mocked_bindings(runApp = function(...) "stopped", .package = "shiny")
  run_app(main, "pin", "http://127.0.0.1:4569", port = 4569)
  expect_identical(read_table(path, "session")$plenum, "none")
  expect_equal(nrow(read_table(path, "votes")), 0)
})

test_that("connections favour durability and wait for busy files before any pragma", {
  path <- withr::local_tempfile()
  init_db(path)
  con <- db(path)
  on.exit(DBI::dbDisconnect(con))
  # NORMAL (1) is SQLite's recommendation for WAL; RSQLite's default is OFF (0).
  expect_equal(DBI::dbGetQuery(con, "PRAGMA synchronous")[[1]], 1)
  expect_equal(DBI::dbGetQuery(con, "PRAGMA busy_timeout")[[1]], 5000)
})
